<Stage>:
	Palla:
		ostacolo1: ostacolo1
		ostacolo2: ostacolo2
		center: self.parent.center

	Ostacolo:
		id: ostacolo1
		pos: 0, 100

	Ostacolo:
		id: ostacolo2
		pos: self.parent.width - self.width, 100


<Palla>:
	size: 50, 50
	canvas:
		Color:
			rgb: 0.3, 0.3, 1
		Ellipse:
			pos: self.pos
			size: self.size


<Ostacolo>:
	width: self.parent.width / 2 - 40
	height: 20
	canvas:
		Color:
			rgb: 1, 1, 0
		Rectangle:
			pos: self.pos
			size: self.size
